init offset = -2


################################################################################
## Game_Map Templete
################################################################################

default Game_Map_MONTH_00or10_1982_templete = {"1": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "2": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "3": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "4": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "5": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "6": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "7": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "8": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "9": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "10": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "11": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "12": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    }
                                }


################################################################################
## Game_Map 三月上棋盘
################################################################################

default Game_Map_march_0_1982 = {"1": { "short_description":"美术馆计划展出裸体塑像“女教皇”。",
                                        "hot":2,
                                        "explore_point":10,
                                        "times":5,
                                        "requirement":None,
                                        "detail": [ "波克先锋艺术展本月18日在巴特美术馆内举行，展出艺术家波克·里拉的画作，雕塑，以及其他艺术作品。",
                                                    "波克最著名的作品也将在展览中亮相，这件名为“女教皇”的裸体雕塑充分地展现了女性的肉体之美，也因此广受争议。",
                                                    "此次引进“女教皇”在国内引发反对声浪，如此大幅度裸露，是否是假“艺术”之名行低俗之实？",
                                                    "该作品以女教皇为名，是否有侮辱宗教之嫌？波克本人则表示，不能充分领略“女教皇”的美好是一种难以想象的损失。"],
                                        "opt1":"波克艺术展将在国家巴特美术馆举行",
                                        "opt1_result":{"艺术":1, "压力":2},
                                        "opt2":"尺度大到难以想象，“艺术”是“低俗”的挡箭牌吗？",
                                        "opt2_result":{"社会":1, "煽情":1, "压力":5}
                                    },
                                "2": { "short_description":"十年来零降雪的L市突然下起了大雪",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":4,
                                        "requirement":None,
                                        "detail":[  "没有一个L市居民能够预料到能在四月，在以炎热著称的L市看到飞雪。昨日，十年来零降雪的L市突然降温，随后落下大雪，并持续了整整一天。",
                                                    "对于这样异常天气，几乎所有人都表达了自己的担忧，只有仍不懂事的孩子们在街头扬起雪花表达内心的喜悦。",
                                                    "有些人认定这是世界末日的前兆，一度沉寂已久的末日论又重新抬起头来，但气象专家称这仍在正常范围之内，不需要恐慌。"],
                                        "opt1":"异常降雪！“世界末日”前兆引恐慌",
                                        "opt1_result":{"煽情":1, "压力":5},
                                        "opt2":"L市异常降雪，出行需注意保暖",
                                        "opt2_result":{"客观":1, "压力":2}
                                    },
                                "3": { "short_description":"K市山火仍未扑灭，千人上山救火",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":2,
                                        "requirement":None,
                                        "detail":[  "由于天气炎热，K市山火频发，目前参与灭火的人数已达1000，其中包括超过700名居民组成的志愿者。另有数千人由于山火被迫疏散。"],
                                        "opt1":"欧特朗山火肆虐，数千人志愿参与灭火",
                                        "opt1_result":{"社会":1, "压力":2},
                                        "opt2":"欧特朗山火继续扩大，市民不安自救",
                                        "opt2_result":{"社会":1, "自由主义":1, "压力":3}
                                    },
                                "4": { "short_description":"沃克街区发现一具男童的尸体，疑似被工头虐待致死",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":1,
                                        "requirement":None,
                                        "detail":[  "死者身上有被殴打的痕迹，男孩母亲称工头曾多次虐打过死者，但被工头否认。其母认定是印刷厂的过失。目前，该男童的母亲仍留在印刷厂门口痛哭。"],
                                        "opt1":"工头体罚，13岁童工惨死街头",
                                        "opt1_result":{"压力":2},
                                        "opt2":"男童惨死街头，政府何时保护好孩子？",
                                        "opt2_result":{"煽情":1, "政治":-1, "压力":5, "社会":1}
                                    },
                                "5": { "short_description":"鹿角胡同内发现一具被斩首的儿童尸体",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":4,
                                        "requirement":None,
                                        "detail":[  "10日，凌晨警方接到报案，鹿角胡同内发现一具儿童尸体。死者11岁，凶手手段残忍，尸体身中数刀，身首分离，警方根据判断用来切断头部的凶器应当是锯齿状工具。",
                                                    "附近居民表示，当晚未听到任何响动或惨叫。目前凶手仍未找到，警方正全力调查案件，增加巡逻人手保障市民的安全。这也是新署长上任以来的第一桩凶杀案。"],
                                        "opt1":"新署长的第一案：鹿角巷惊现幼童尸体",
                                        "opt1_result":{"客观":1, "压力":2, "金钱":100, "Extra":"获得“《斩首杰克连环杀人案》”素材"},
                                        "opt2":"残忍切下死者头部，斩首凶手仍在逃",
                                        "opt2_result":{"煽情":1, "泽维尔认可":-1, "压力":3, "Extra":"获得“《斩首杰克连环杀人案》”素材"}
                                    },
                                "6": { "short_description":"一栋房子上方聚集了大量猫头鹰？",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":2,
                                        "requirement":None,
                                        "detail":[  "近日烟囱街的一栋房屋出现奇景，几十只猫头鹰降落在屋顶上，持续了整天未离去。猫头鹰久久不散的原因还不明确，该房屋的屋主拒绝与本报记者沟通。邻居声称曾目击猫头鹰嘴上叼着信件。截至目前为止，猫头鹰仍在该房屋上逗留。"],
                                        "opt1":"烟囱街惊现猫头鹰屋奇景",
                                        "opt1_result":{"":0},
                                        "opt2":"猫头鹰成群聚集房顶，猫头鹰屋有何玄机",
                                        "opt2_result":{"":0}
                                    },
                                "7": { "short_description":"古董店老板横死店中，尸体发黑，疑似被毒杀。",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":3,
                                        "requirement":None,
                                        "detail":[  "五号大街古董店业主莫德尔先生昨日被发现横尸店中，尸体呈现不正常紫黑色。警方调查后认定为毒杀。",
                                                    "目前其妻已投案自首，该女子对罪行供认不讳，称是因为不堪丈夫的虐待才对其下毒。"],
                                        "opt1":"最毒妇人心，古董店主被妻毒杀",
                                        "opt1_result":{"":0},
                                        "opt2":"女子不堪虐待，杀死丈夫后投案",
                                        "opt2_result":{"":0}
                                    },
                                "8": { "short_description":"钢琴厂焚烧钢琴",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":5,
                                        "requirement":None,
                                        "detail":[  "由于钢琴滞销，洋赛琴厂将滞销的钢琴统一烧毁。负责人解释，去年来钢琴销售额持续下滑，大部分人根本呢负担不起艺术。烧毁钢琴是为了防止将其出售给非目标人群，损害品牌价值。",
                                                    "“他们明明可以不把价钱定到那么高的！”一位居民愤愤不平地说"],
                                        "opt1":"大众购买力不足，工厂无奈焚烧钢琴",
                                        "opt1_result":{"":0},
                                        "opt2":"宁可烧毁也不卖给穷人！工厂焚琴火光冲天",
                                        "opt2_result":{"":0}
                                    },
                                "9": { "short_description":"国家地理学会联合探险队于马可比沙漠中发现了古文明遗迹",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":2,
                                        "requirement":None,
                                        "detail":[  "上月，国家地理学会联合探险队于马可比沙漠中发现了古文明遗迹，传闻中的文明“玛娜”被证明真正存在，探险队领头人海尔森·宾西给它的废墟拍摄了第一组照片。",
                                                    "照片上只是一瞥，既能感到时光之伟力，也能体会到人类智慧之灿烂。一直以来，诸多传说围绕着玛娜古文明，玛娜文明曾一度繁盛至极，又几乎在一夜之间被抹去。其中缘由至今仍是个谜。",
                                                    "玛娜文明遗迹的发现让人类有机会一探真相，揭开玛娜文明的神秘面纱。"],
                                        "opt1":"考古惊天发现：传说中的玛娜古城是真的！",
                                        "opt1_result":{"":0},
                                        "opt2":"文明的最后痕迹：探险队发现失落古城",
                                        "opt2_result":{"":0}
                                    },
                                "10": { "short_description":"音乐会上居然发生了斗殴事件。作曲家被听众痛打。",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":3,
                                        "requirement":None,
                                        "detail":[  "本月7日，一场特殊的音乐会在德林音乐厅举行，表演者兰德尔·洛佩兹以其实验性质的“音乐”闻名，围绕其古怪音乐的争议从未停止过。",
                                                    "表演途中，由于无法忍受兰德尔演奏的音乐，一位观众冲上台当场掌掴兰德尔，随即在兰德尔的支持者和反对者之间爆发了冲突。音乐会因此被强制关闭。",
                                                    "“他被打也是活该，他的曲子连噪音都不如，根本是在侮辱音乐！”一位参加了音乐会的观众说。"],
                                        "opt1":"音乐实在太难听，听众愤怒痛打作曲家",
                                        "opt1_result":{"":0},
                                        "opt2":"听众拒绝接受全新音乐形式，当众殴打作曲家",
                                        "opt2_result":{"":0}
                                    },
                                "11": { "short_description":"工伤女工们要求赔偿，被厂主拒绝",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":1,
                                        "requirement":None,
                                        "detail":[  "近日，泰蓝机械加工厂的几名女工因为骨骼肿瘤而被工厂辞退。据女工们所说，肿瘤是因为女工们在工厂加工时接触的涂料含有放射性物质“镭”。目前，工厂中因患病而被辞退的人数已经超过60，其中数人已经去世。",
                                                    "工人们组成维权协会，聚集在工厂门口，抗议工厂辞退患病女工，要求给予赔偿。但工厂拒绝承认涂料中含有镭，拒绝赔偿医疗费。"],
                                        "opt1":"女工因含镭涂料患病，工厂拒绝赔偿",
                                        "opt1_result":{"":0},
                                        "opt2":"毒涂料致死工人，黑心厂主拒绝赔偿",
                                        "opt2_result":{"":0}
                                    },
                                "12": { "short_description":"新书《逃离地狱》大卖，该书讲述了雷耶尔独裁政府的暴行。",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":3,
                                        "requirement":None,
                                        "detail":[  "上月，拟科出版社推出新书《逃离地狱》，一经推出即成为热点，仅在第一周就狂卖4000册。该书讲述了主角因政见不合，被雷耶尔共和国总统塔奇克投入集中营中关押8年，朋友们被虐待至死，只身一人逃出的故事。",
                                                    "该书改编自作者真实经历，1843年，作者古雷克因公开发文指责总统独裁，未经审判即被关押。1847年，他伪装成尸体逃出集中营，逃亡贝莱，获得了自由。"],
                                        "opt1":"雷耶尔难民新书《逃离地狱》大热",
                                        "opt1_result":{"":0},
                                        "opt2":"难民控诉独裁政府暴行：揭秘雷耶尔集中营",
                                        "opt2_result":{"":0}
                                    }
                                }


################################################################################
## Game_Map 三月下棋盘
################################################################################

default Game_Map_march_1_1982 = {"1": { "short_description":"男子掉下水井，发现大量金条",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  "昨日，一位幸运男子失足坠井，意外发现了藏在井底的10KG金条，这批金条为特别打造，统一印有羽翼标记。目前尚不知道是何人把金条藏在了井里。"],
                                        "opt1":"因祸得10KG黄金！男子一夜暴富",
                                        "opt1_result":{"":0},
                                        "opt2":"男子坠井发现神秘井下藏金",
                                        "opt2_result":{"":0}
                                    },
                                "2": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "3": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "4": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "5": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "6": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "7": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "8": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "9": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "10": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "11": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    },
                                "12": { "short_description":"",
                                        "hot":0,
                                        "explore_point":0,
                                        "times":0,
                                        "requirement":None,
                                        "detail":[  ""],
                                        "opt1":"",
                                        "opt1_result":{"":0},
                                        "opt2":"",
                                        "opt2_result":{"":0}
                                    }
                                }

